### PR TITLE
django 1.8 compatibility: rename query_set to queryset

### PR DESCRIPTION
**Pull request by i-trofimtschuk**

### CODE REVIEW

**Comment by matthiask** [comment]
Thanks!

**Comment by mjl** [comment]
Does this break compat with earlier, still supported Django releases?

**Comment by matthiask** [comment]
It does not, because 1.11 only supports Django 1.6 or better. The query_set -> queryset renaming happened with Django 1.6.

**Comment by matthiask** [comment]
I did not see this specific instance because I didn't use `FEINCMS_TREE_EDITOR_INCLUDE_ANCESTORS`.

**Pull request merged**
