### PR TITLE
DON'T MERGE.

### PR DESCRIPTION
**Pull request by matthiask**
Work in progress towards FeinCMS 2 (or something).

Use this pull request for discussion and feedback. Also, hating and flaming if you really have to (but please don't)

### CODE REVIEW

**Comment by michaelkuty** [comment]
I think that moving views.decorators.standalone to new location without deprecated warning instantly breaks all feincms modules. I think that use same location with deprecated warning for example to 2.0.2 release makes some time to adopt to new location without breaking all related stuff.
If you want, I can create these stuff with warning for importing from wrong location.

**Comment by matthiask** [comment]
Yes, thanks. I'll certainly roll another release in the 1.x series to help people prepare for the changes (should we go forward with this branch at all)

**Comment by michaelkuty** [comment]
Hi,
today i make some testing with new release and if I have installed 2.0a1 everything works well, but if I have installed 2.0a2 my application fails with
 
    self._wrapped = Settings(settings_module)
    File "/srv/leonardo/sites/majklk/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
      mod = importlib.import_module(self.SETTINGS_MODULE)
    File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
      __import__(name)
    File "/srv/leonardo/sites/majklk/leonardo/leonardo/settings.py", line 423, in <module>
      ApplicationWidget, APPLICATIONS=APPLICATION_CHOICES)
    File "/srv/leonardo/sites/majklk/local/lib/python2.7/site-packages/feincms/models.py", line 631, in create_content_type
      cls._create_content_base()
    File "/srv/leonardo/sites/majklk/local/lib/python2.7/site-packages/feincms/models.py", line 459, in _create_content_base
      cls._needs_templates()
    File "/srv/leonardo/sites/majklk/local/lib/python2.7/site-packages/feincms/models.py", line 749, in _needs_templates
      ' template or one region on %s.' % cls.__name__)
     django.core.exceptions.ImproperlyConfigured: You need to register at least one template or one region on Page.

please do you have any idea what is wrong ? I check history of this file and i don't see anything what should breaks this behavior..

thanks for your time

**Comment by matthiask** [comment]
Hi,

Not sure why this would happen. Maybe you get an import error somewhere which leads to your `register_templates` statement not being run? Maybe because I removed much old code in 2.0a2...

Especially the removal of `feincms.content.*` and `feincms.module.extensions.*` come to mind...: https://github.com/feincms/feincms/compare/b76f05b0b33fdc258238b9a8859de95fd0d5bf99...matthiask:0b4bbe4c6f8555349238bb8da1d5099314799e03

**Comment by matthiask** [comment]
PS: The reason why I want to remove lots of old stuff for 2.0 is that I want developing FeinCMS to be more fun again, and maybe also easier for newcomers because there's less to think about, less backward compatibility concerns (less support for old Django versions -- FeinCMS 1.11 was compatible back to Django 1.4...)

Also, priorities shifted a bit in the last years, but I'm certainly not ready to abandon FeinCMS at all, especially not after looking around the Django-based CMS landscape.

**Comment by michaelkuty** [comment]
OK, I'm really stupid, next time i will do more introspecting before I make question to you.

I'm so happy when I reading your last lines. We have same opinion on the CMS landscape.
Sometimes when i doing introspection some behavior in feincms, I do think that you are genius and feincms is really nice piece of art, but as you said are there much useless stuff.

Me and my friend are working on cms (leonardocms) on top feincms that extends its functions and standardises some areas, brings more widgets and more specialised application integration (oscarcsm) which provides better experience for newcomers. Would you be interested to integrate some of the features we have developed into feincms and we could transform leonardo to more flexible modules.

**Comment by matthiask** [comment]
No need to chastise yourself :-)  and thanks.

Regarding integrating stuff into FeinCMS: It depends. If it can't be done easily outside FeinCMS, and if it would help a big majority of FeinCMS users I'll look into merging additional code. The downside for me is that this also means maintaining additional code, so it has to be a big plus for (almost) everybody.

Do you have concrete proposals?

**Comment by mjl** [comment]
> Regarding integrating stuff into FeinCMS: It depends. If it can't be done easily outside FeinCMS, and if it would help a big majority of FeinCMS users I'll look into merging additional code. The downside for me is that this also means maintaining additional code, so it has to be a big plus for (almost) everybody.

  We really need a simple way to publish additional modules. That's not a new idea, but we still haven't something really useful at the moment.

**Pull request closed without merging**
