### PR TITLE
fixed (fields.W340) null has no effect on ManyToManyField.

### PR DESCRIPTION
**Pull request by michaelkuty**

### CODE REVIEW

**Comment by matthiask** [comment]
Thank you! That's not the only place where this should be fixed in FeinCMS' source code; the m2m relation between mediafiles and categories come to mind as well.

Can you add removals for all other occurrences of W340 too? Would be awesome!

**Comment by michaelkuty** [comment]
yes, sure
sorry for not fully cleaned, but Leonardo CMS does not use standard feincms media and i didn't see this occurrences

**Comment by michaelkuty** [comment]
I think, that is mergeable to new release.

**Comment by matthiask** [comment]
Thanks!

**Pull request merged**
