### PR TITLE
fix #695

### LINKED ISSUE #695: TypeError: __init__() missing 1 required positional argument: 'on_delete'
```python
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/djangoapp/simplepages/models.py", line 4, in <module>
    from feincms.contents import RichTextContent
  File "/usr/local/lib/python3.8/site-packages/feincms/contents.py", line 3, in <module>
    from feincms.content.filer.models import *  # noqa
  File "/usr/local/lib/python3.8/site-packages/feincms/content/filer/models.py", line 52, in <module>
    class FilerFileContent(ContentWithFilerFile):
  File "/usr/local/lib/python3.8/site-packages/feincms/content/filer/models.py", line 53, in FilerFileContent
    mediafile = FilerFileField(verbose_name=_("file"), related_name="+")
  File "/usr/local/lib/python3.8/site-packages/filer/fields/file.py", line 136, in __init__
    super(FilerFileField, self).__init__(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by bashu** [comment]
to @matthiask what about releasing 1.18.1?

**Comment by matthiask** [comment]
Thanks!

**Comment by matthiask** [comment]
> 
> 
> to @matthiask what about releasing 1.18.1?

I pushed 1.19, enough changes :)

**Comment by bashu** [comment]
to @matthiask 🚀

**Pull request merged**
