### PR TITLE
fixed url pattern kwargs

### PR DESCRIPTION
**Pull request by lenz**
Hi Matthias,

looking at the documentation url pattern kwargs like
url(r'^$', handler, {'path': '/rootpage'}, name='feincms_home')
should work and they have been working but at the moment they don´t.

This is because the super class method
feincms.module.mixins.ContentView.dispatch() calls the sub class method Handler.get_object()
without arguments.
Therefore one must pass args and kwargs to the get_objects method or use self.kwargs wich is explicitly set by the super class method feincms.module.mixins.ContentView.dispatch()

The pull request uses the latter approach.
If you think we should do it in a different way just tell me and I change it.

Cheers

Lenz

### CODE REVIEW

**Comment by matthiask** [comment]
Thank you! I worry a bit about the backwards compatibility implications of this. 

The code and the docs do not agree; should the code or the docs be changed?

If we change the code we should add a fallback from kwargs to args, and warn loudly if a value is only found in args. 

It also seems to me that the changed view would not work with the bundled `feincms.urls` since the path isn't passed as keyword but as a positional argument there.

**Comment by lenz** [comment]
Sorry for the delay!
Correct me if I am overseeing something:
For all the common use cases I don´t see any backwards compatibility implications because the django.conf.urls.url function does not take a list of args to pass to the dispatch method. I only takes kwargs to pass on. Therefore the self.args variable may has never been used because it is just not possible to use it from the urls.py (bundled or own).

**Comment by matthiask** [comment]
Thanks for the explanation.

The bundled `feincms/urls.py` URLconf module contains the following line:
```
    url(r'^(.*)/$', handler, name='feincms_handler'),
```

That is, the path is passed as a positional argument, not as a keyword argument. I suspect that the change you made activates the fallback in `Page.objects.for_request` from path to `request.path_info` etc... which isn't what we want in the general case.

A fallback from `kwargs` to `args` should work better, maybe? Something like

 ```
    if 'path' in self.kwargs:
        path = self.kwargs['path']
    elif self.args:
        path = self.args[0]
``` 

That should solve your issue and not break anything for anyone else, no?

**Comment by matthiask** [comment]
I committed my suggestion from above. I hope this fixes the issue for you.

**Pull request closed without merging**
