### PR TITLE
fixed Readonly fields are not included #559

### PR DESCRIPTION
**Pull request by michaelkuty**
i don't know if is right solution but works, maybe better fields sort, because now is as last items, but is logical for me as user, because first i want editable(required) and after these fields i want see remain fields

### CODE REVIEW

**Comment by michaelkuty** [comment]
i try test before my changes and exceptions is same as in the test with python 3+
django.db.models.fields.FieldDoesNotExist: MediaFile has no field named 'admin_thumbnail'

please i need help with this, for me works well and i don't know why i broke media library in this case

**Comment by nanuxbe** [comment]
Unless someone else wants to step in, I'll take a look at it this weekend.

**Comment by nanuxbe** [comment]
It would appear from the error message you are getting that the error is related to http://stackoverflow.com/questions/23587426/pil-open-method-not-working-with-bytesio and come from https://github.com/feincms/feincms/blob/53ec56bea98cd7d9c1b58e5dd753d467106a3eb5/feincms/templatetags/feincms_thumbnail.py#L106.

I guess that
a) python 2 is more forgiving about it
b) it's probably a matter of fixing the original test (the problem was not encountered before since the field was not loaded)

Also, before fixing the bug, it might be nice to write a test that fails to make sure your fix actually works.

**Comment by nanuxbe** [comment]
And actually you didn't break MediaLibrary. The MediaLibrary error is independent of the failing test which is:

    ======================================================================
    FAIL: test_25_applicationcontent (testapp.tests.test_page.PagesTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/feincms/feincms/tests/testapp/tests/test_page.py", line 1352, in test_25_applicationcontent
        'exclusive_subpages')
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/django/test/testcases.py", line 351, in assertContains
        msg_prefix + "Couldn't find %s in response" % text_repr)
    AssertionError: False is not true : Couldn't find 'exclusive_subpages' in response
    ----------------------------------------------------------------------

**Comment by michaelkuty** [comment]
yes i know, can you fix original issue ? showing read only fields in admin ?

**Comment by nanuxbe** [comment]
I'm looking at it

**Comment by matthiask** [comment]
That's an area where tests are required to show that the issue is fixed. The formset handling code breaks from time to time because of changes in Django, and without tests we will not be able to keep everything working as it should.

**Comment by michaelkuty** [comment]
yes i know, i spent a lot of time inspecting this issue and i fold that, Because i haven't time, now i'm under heavy development new platform, which build on FeinCMS(https://github.com/django-leonardo/django-leonardo)
**thanks a lot of for new release and what you are doing**
yesterday i test new FeinCMS and Django 1.8 and works really well, i fixed some 3rd party apps and from this time is Leonardo 1.8 stable

I implemented pretty front-end edit as you can see here http://demo.cms.robotice.cz/admin 
login root
password admin
and after logged in standard enabling http://demo.cms.robotice.cz?frontend_editing=1
I think, that your concept, which was removed in this release is good start point for implementing this feature, but yes not must be in core.

if you have some time, you could insopect Leonardo - admin, frontend and implemented widgets and module style.
Please send me a feedback mail@majklk.cz or write here
We are still on start and for now we work on cleanup core features cms,media and module system, but most of dirty works is done

big thanks for your time

and as i mention i haven't capacity for proposal correct solution for this issue, you could close this merge

**Pull request closed without merging**
