### PR TITLE
add Django 1.10 support (drop Django < 1.8)

### PR DESCRIPTION
**Pull request by b45ch1**
PR to #636.

I ran tests for 
```
tox -e py27-django18
tox -e py27-django19
tox -e py34-django18
```
without errors:

```
Ran 58 tests in 6.574s

OK (skipped=1)
```

To keep Django <1.8 support, one could use https://github.com/arteria/django-compat/issues/38

### CODE REVIEW

**Comment by matthiask** [comment]
Thank you! 

I have a doubt regarding the change from `context_instance=RequestContext(request)` to `request=request`. Are values from context processors still available inside content type's templates? I'm not sure whether we have a test for that.

Apart from this everything looks good!

**Comment by b45ch1** [comment]
Values from the context processors _should_ be available. But I have not verified it.

**Comment by matthiask** [comment]
We are not there yet. No django-mptt release supports Django 1.10 yet ([django-mptt-nomagic](https://pypi.python.org/pypi/django-mptt-nomagic/) supports it, but I hope that I'll be able to retire this package soon in favor of django-mptt).

Ongoing work is here: https://travis-ci.org/feincms/feincms/builds/150583456 / https://github.com/feincms/feincms/tree/next

**Comment by matthiask** [comment]
Thank you! Your commits have been merged to https://github.com/feincms/feincms/tree/next and will end up in the next release of FeinCMS.

**Pull request closed without merging**
